#!/usr/bin/env bash

set -e

if [ "$#" -ne 2 ]; then
  echo -e "Please provide AUR package name and GPG key to build\nUsage: build-aur <package-name> <key-id>"
  exit 1
fi

package=$1
key=$2

chown -R makepkg:users /build

sudo -u makepkg git clone --depth 1 https://aur.archlinux.org/$package.git /build

/build-pkgbuild $key
