#!/usr/bin/env bash

set -e

if [ "$#" -ne 2 ]; then
  echo -e "Please provide git repository to build."
  echo -e "The repository must contain a build.sh script within it's pkg directory."
  echo -e "Usage: build-git <package-name> <key-id>"
  exit 1
fi

git_repo=$1
key=$2

cd /build
git clone $git_repo
chown -R makepkg:users /build

cd $(ls | head)/pkg/
bash build.sh

pacman -Sy
sudo -u makepkg makepkg --noconfirm -sf --sign --key "$key"

mv $package*.pkg.tar.xz /pkg
