#!/usr/bin/env bash

set -Eeuo pipefail

if [ "$#" -ne 2 ]; then
  echo -e "Please provide git repository to build."
  echo -e "The repository must contain a build.sh script within it's pkg directory."
  echo -e "Usage: build-git <git-repo> <repo-name>"
  exit 1
fi

git_repo=$1
repo_name=$2

# Sort out the build directory
if [ -d /build ]; then
    rm -r /build
fi

mkdir /build
chown -R makepkg /build
cd /build

# Clone the package
git clone $git_repo
chown -R makepkg:users /build

# Run the build script
cd $(ls | head)/pkg/
bash build.sh

# Build the package and update the repo DB
pacman -Sy
sudo -u makepkg aur build -sf -d "${repo_name}" -- --noconfirm

