#!/bin/bash
#
# build-aur
#
# Builds a specified package from the AUR, including any dependencies it may 
# have, and adds them to the local repository.
#

set -Eeuo pipefail

# Required environment variables
region=${AWS_REGION}            # The AWS region the SQS queue is contained in
repo_name=${REPO_NAME}          # The name of the DB file within the repository
arch=${REPO_ARCH}               # The architecture to build for (eg. x86_64)

if [ "$#" -ne 2 ]; then
  echo -e "Please provide AUR package name and bucket"
  echo -e "Usage: build-aur <repo-bucket> <package-name>"
  exit 1
fi

repo_bucket="$1"
package="$2"

echo "build-aur: Creating build directory"
if [ -d /build ]; then
    rm -r build
fi

mkdir /build
chown -R makepkg /build

echo "build-aur: Building package"
sudo -u makepkg aur sync \
    -Srf --no-confirm --no-view --no-ver-argv \
    -d "${repo_name}" \
    -r "/${repo_bucket}/${arch}" \
    "${package}"

# Sync up DB and package to s3
echo "build-aur: Syncing repo DB and uploading to s3"
aws s3 sync \
    --region ${region} \
    --acl public-read \
    --follow-symlinks \
    /${repo_bucket}/${arch}/ s3://${repo_bucket}/${arch}/

echo "build-aur: Build complete"
