#!/bin/bash
#
# build-aur
#
# Builds a specified package from the AUR, including any dependencies it may 
# have, and adds them to the local repository.
#

set -uo pipefail

# Required environment variables
region=${AWS_REGION}            # The AWS region the SQS queue is contained in
repo_name=${REPO_NAME}          # The name of the DB file within the repository
repo_bucket=${REPO_BUCKET}      # The bucket name containing the repo files within AWS
arch=${REPO_ARCH}               # The architecture to build for (eg. x86_64)

if [ "$#" -ne 1 ]; then
  echo -e "Please provide AUR package name"
  echo -e "Usage: build-aur <package-name>"
  exit 1
fi

package="$1"

if [ -d /build ]; then
    rm -r build
fi

mkdir /build
chown -R makepkg /build

sudo -u makepkg aur sync \
    -snr --no-view \
    -d "${repo_name}" \
    -r "/${repo_bucket}/${arch}" \
    "${package}"

# Sync up DB and package to s3
aws s3 sync \
    --region ${region} \
    --acl public-read \
    --follow-symlinks \
    /${repo_bucket}/${arch}/ s3://${repo_bucket}/${arch}/

