#!/bin/bash
#
# reset
#
# Sends a failure notification to the fanout queue to allow it to be handled.
#

set -uo pipefail
trap 's=$?; /send-pushover "Reset Error" "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
IFS=$'\n\t'

# Requried environment variables
region=${AWS_REGION}                    # The AWS region the SQS queue is contained in
fanout_queue=${FANOUT_QUEUE}            # URL of the queue to send a completion or failure notification to
pkg="$0"

if [ -z "$pkg" ]; then
    echo "Failure happened before a package was built"
    exit 1
fi

echo "Notifying queue of completion"
aws sqs send-message \
    --region ${region} \
    --queue-url ${fanout_queue} \
    --message-body "{\"PackageName\": \"${pkg}\", \"BuildStatus\": \"Failed\"}"

