#!/bin/bash
#
# reset
#
# Sends a failure notification to the fanout queue to allow it to be handled and remove the package from
# the queue to prevent further attempts at building.
#

set -Eeuo pipefail

# Requried environment variables
queue=${SQS_QUEUE_URL}                  # The URL of the SQS queue
region=${AWS_REGION}                    # The AWS region the SQS queue is contained in
fanout_queue=${FANOUT_QUEUE}            # URL of the queue to send a completion or failure notification to
pkg="$1"
receipt_handle="$2"

if [ -z "$pkg" ]; then
    echo "Failure happened before a package was built"
    exit 1
fi

echo "Notifying queue of failure"
aws sqs send-message \
    --region ${region} \
    --queue-url ${fanout_queue} \
    --message-body "{\"PackageName\": \"${pkg}\", \"BuildStatus\": \"Failed\"}"

echo "Deleting message..."
aws sqs delete-message \
    --region ${region} \
    --queue-url ${queue} \
    --receipt-handle "${receipt_handle}"

