#!/usr/bin/env bash
# 
# send-pushover
#
# Sends a notification message to a pushover client via their API
#

pushover_token=${PUSHOVER_TOKEN}        # API Key used for the pushover application
pushover_user=${PUSHOVER_USER}          # User key for pushover notifications

set -e

if [ "$#" -lt 2 ]; then
  echo -e "Usage: pushover-send <title> <message> <stderr_file>"
  exit 1
fi

title=$1
message=$2
if [ ! -z "$3" ]; then
    message=$(echo "$message\n"; cat "$3")
fi

curl -s \
    --form-string "token=${pushover_token}" \
    --form-string "user=${pushover_user}" \
    --form-string "title=${title}" \
    --form-string "message=${message}" \
    "https://api.pushover.net/1/messages.json"
