#!/bin/bash
#
# setup-verification-key
#
# Pulls down keys that are used to sign various AUR packages.
#

set -Eeuo pipefail

err_report() {
    local parent_lineno="$1"
    local message="$2"
    local code="${3:-1}"

    if [[ -n "$message" ]]; then
        echo "$0: ${parent_lineno}: $message" >> err.txt
    else
        echo "$0: ${parent_lineno}" >> err.txt
    fi
    exit $code
}
trap 'err_report ${LINENO} "$0: ${BASH_COMMAND}" $?' ERR

# Requried environment variables
region=${AWS_REGION}        # The AWS region the SQS queue is contained in
aur_keys=${AUR_KEYS}        # Name of public signing keys within the parameter store

sudo -u makepkg gpg --recv-keys $(
    aws ssm get-parameter \
        --region ${region} \
        --name ${aur_keys} |
        jq -r ".Parameter.Value" |
        sed 's/,/ /g'
)
